# Generated by Django 3.2.16 on 2023-02-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPPLIER', 'Supplier'), ('MANUFACTURER', 'Manufacturer'), ('RETAILER', 'Retailer')], max_length=30),
        ),
    ]
