# Generated by Django 4.1.7 on 2023-02-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_supplierdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierdetails",
            name="contact_person",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="supplierdetails",
            name="gst_number",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplierdetails",
            name="qulaity_score",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supplierdetails",
            name="phone_number",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
