# Generated by Django 4.1.7 on 2023-02-28 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_supplierproduct"),
    ]

    operations = [
        migrations.RenameField(
            model_name="supplierdetails",
            old_name="qulaity_score",
            new_name="quality_score",
        ),
    ]
