# Generated by Django 4.1.7 on 2023-03-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_rename_qulaity_score_supplierdetails_quality_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierdetails",
            name="address",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="supplierdetails",
            name="contact_person",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="supplierdetails",
            name="gst_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="supplierdetails",
            name="phone_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="supplierdetails",
            name="quality_score",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
