# Generated by Django 4.1.7 on 2023-03-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_supplierdetails_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierproduct",
            name="type",
            field=models.CharField(
                choices=[
                    ("Dairy products", "DAIRY PRODUCTS"),
                    ("Fruits", "FRUITS"),
                    ("Vegetables", "VEGETABLES"),
                    ("Meat and poultry", "MEAT AND POULTRY"),
                    ("Grains and cereals", "Grains and cereals"),
                    ("Baked goods and breads", "Baked goods and breads"),
                    ("Beverages", "Beverages"),
                    ("Snack foods", "Snack foods"),
                    ("Condiments and spices", "Condiments and spices"),
                ],
                max_length=50,
            ),
        ),
    ]
