# Generated by Django 4.1.7 on 2023-03-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_alter_supplierproduct_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_details_verified",
            field=models.BooleanField(default=False),
        ),
    ]
