# Generated by Django 4.1.7 on 2023-03-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_user_is_details_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_details_verified",
        ),
        migrations.AddField(
            model_name="supplierdetails",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Rejected", "Rejected"),
                    ("Approved", "Approved"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
