# Generated by Django 4.1.7 on 2023-03-17 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_supplierorder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplierorder",
            name="manufacturer_or_retailer",
        ),
        migrations.AddField(
            model_name="supplierorder",
            name="manufacturer_or_retailers",
            field=models.ForeignKey(
                default=1,
                limit_choices_to={"user_type__in": ["manufacturer", "retailer"]},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
