# Generated by Django 4.1.7 on 2023-03-17 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_remove_supplierorder_manufacturer_or_retailer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierorder",
            name="manufacturer_or_retailers",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
