# Generated by Django 4.1.7 on 2023-03-17 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_alter_supplierorder_manufacturer_or_retailers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierorder",
            name="manufacturer_or_retailers",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ["MANUFACTURER", "RETAILER"]},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
