# Generated by Django 4.1.7 on 2023-03-17 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0020_alter_supplierorder_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierorder",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="home.supplierdetails",
            ),
        ),
    ]
