# Generated by Django 4.1.7 on 2023-03-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_alter_supplierorder_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierorder",
            name="totalamount",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supplierorder",
            name="delivery_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
