# Generated by Django 4.1.7 on 2023-03-22 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_supplierorder_totalamount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierorder",
            name="manufacturer_or_retailers",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ["MANUFACTURER", "RETAILER"]},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_placed_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="supplierorder",
            name="supplier",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ["SUPPLIER"]},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_received_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
