# Generated by Django 4.1.7 on 2023-03-28 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0024_supplierorder_order_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierOrderRecord",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("order_id", models.IntegerField()),
                ("quantity", models.IntegerField()),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                ("delivery_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("totalamount", models.FloatField()),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("in_cart", "In Cart"),
                            ("order_placed", "Order Placed"),
                        ],
                        default="in_cart",
                        max_length=20,
                    ),
                ),
                (
                    "manufacturer_or_retailers",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["MANUFACTURER", "RETAILER"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_placed_by_record",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_record",
                        to="home.supplierproduct",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["SUPPLIER"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_received_by_record",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
