# Generated by Django 4.1.7 on 2023-03-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0025_supplierorderrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierorderrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                    ("CUSTOMER_CANCELLED", "Customer_Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
