# Generated by Django 4.1.7 on 2023-03-30 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0027_alter_supplierorderrecord_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManufacturerProduct",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quality", models.IntegerField()),
                ("quantity", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Dairy products", "DAIRY PRODUCTS"),
                            ("Fruits", "FRUITS"),
                            ("Vegetables", "VEGETABLES"),
                            ("Meat and poultry", "MEAT AND POULTRY"),
                            ("Grains and cereals", "Grains and cereals"),
                            ("Baked goods and breads", "Baked goods and breads"),
                            ("Beverages", "Beverages"),
                            ("Snack foods", "Snack foods"),
                            ("Condiments and spices", "Condiments and spices"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manufacturerproducts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
