# Generated by Django 4.1.7 on 2023-03-31 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0029_manufacturerorderrecord_manufacturerorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturerorder",
            name="manufacturer_or_retailers",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ["RETAILER"]},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manu_orders_placed_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="manufacturerorder",
            name="supplier",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ["MANUFACTURER"]},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manu_orders_received_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
