# Generated by Django 4.1.7 on 2023-03-31 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0030_alter_manufacturerorder_manufacturer_or_retailers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturerorder",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manu_orders",
                to="home.manufacturerproduct",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturerorderrecord",
            name="manufacturer_or_retailers",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ["RETAILER"]},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manu_orders_placed_by_record",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="manufacturerorderrecord",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manu_orders_record",
                to="home.manufacturerproduct",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturerorderrecord",
            name="supplier",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ["MANUFACTURER"]},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manu_orders_received_by_record",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
