# Generated by Django 4.1.7 on 2023-04-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0031_alter_manufacturerorder_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturerorder",
            name="credit_periiod",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="manufacturerorderrecord",
            name="credit_periiod",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="manufacturerproduct",
            name="credit_periiod",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supplierorder",
            name="credit_periiod",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supplierorderrecord",
            name="credit_periiod",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
