# Generated by Django 4.1.7 on 2023-04-02 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0032_manufacturerorder_credit_periiod_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="manufacturerorder",
            old_name="credit_periiod",
            new_name="credit_period",
        ),
        migrations.RenameField(
            model_name="manufacturerorderrecord",
            old_name="credit_periiod",
            new_name="credit_period",
        ),
        migrations.RenameField(
            model_name="manufacturerproduct",
            old_name="credit_periiod",
            new_name="credit_period",
        ),
        migrations.RenameField(
            model_name="supplierorder",
            old_name="credit_periiod",
            new_name="credit_period",
        ),
        migrations.RenameField(
            model_name="supplierorderrecord",
            old_name="credit_periiod",
            new_name="credit_period",
        ),
    ]
