# Generated by Django 4.1.7 on 2023-04-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0033_rename_credit_periiod_manufacturerorder_credit_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierproduct",
            name="credit_period",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
