# Generated by Django 4.1.7 on 2023-04-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0034_supplierproduct_credit_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturerorderrecord",
            name="rating",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="manufacturerproduct",
            name="review_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="supplierorderrecord",
            name="rating",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="supplierproduct",
            name="review_count",
            field=models.IntegerField(default=0),
        ),
    ]
