# Generated by Django 4.1.7 on 2023-04-03 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0035_manufacturerorderrecord_rating_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alert_count", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="home.manufacturerproduct",
                    ),
                ),
            ],
        ),
    ]
